# Use the C base
language: c

# Linux - use Ubuntu 14.04 Trusty Tahr.
sudo: required
dist: trusty

# Branches que serão compiladas pelo TravisCI.
branches:
  only:
  - ultimate

# Linux - add the Ubuntu restricted tool chain to install GCC 7 package and the standard C library.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - linux-libc-dev
    - gcc-7-multilib
    - g++-7-multilib
    - libcurl4-openssl-dev:i386
    - libpthread-stubs0-dev:i386

env:
  global:
    - COMPILER_VERSION_C=gcc-7
    - COMPILER_VERSION_CXX=g++-7
    - DEPENDENCIES_DIR="${TRAVIS_BUILD_DIR}/dependencies"

# Disable the cache for now; this isn't working quite as expected (and it's in beta)
#cache:
#  directories:
#      - ${DEPENDENCIES_DIR}/xercesc/install/include
#      - ${DEPENDENCIES_DIR}/xercesc/install/lib
    
matrix:
  allow_failures:
    # We allow all Mac builds to fail since we don't have a real Mac to test them.
    - os: osx
  include:
    # Opções de build type disponíveis:
    # Debug, Release, MinSizeRel e RelWithDebInfo
    # A fazer: Gerar .pdb em modo Release.
    #
    # Ubuntu 14.04 Trusty Tahr amd64 (Linux) GCC 7
    - os: linux
      env: BUILD_RULES="-DCMAKE_BUILD_TYPE=Release -DUSE_OPFOR=1 -DUSE_ANGELSCRIPT=0 -DUSE_AS_SQL=0"
    # Mac OS X
    - os: osx
      env: BUILD_RULES="-DCMAKE_BUILD_TYPE=Release -DUSE_OPFOR=1 -DUSE_ANGELSCRIPT=0 -DUSE_AS_SQL=0"

before_install:
  # On Linux, download the 32 bits version of the standard C library.
  # On Mac, just update Homebrew.
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo dpkg --add-architecture i386
      sudo apt-get -qq update
      sudo apt-get install -y linux-libc-dev:i386
    else
      brew update
    fi

install:
  # Prepare the dependencies, build and fake Steam common directories for Travis.
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - STEAMCOMMON_DIR="${TRAVIS_BUILD_DIR}/steam_common"
  - mkdir -p ${DEPS_DIR} && mkdir -p ${STEAMCOMMON_DIR} && mkdir -p ${STEAMCOMMON_DIR} && mkdir -p ${STEAMCOMMON_DIR}/Half-Life && cd ${DEPS_DIR}
  # Get the latest CMake version and Make symlinks so it can use VGUI properly.
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      CMAKE_URL="http://www.cmake.org/files/v3.11/cmake-3.11.4-Darwin-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/CMake.app/Contents/bin:${PATH}
    fi

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      COMPILER_SETTINGS="-DCMAKE_CXX_COMPILER=${COMPILER_VERSION_CXX} -DCMAKE_C_COMPILER=${COMPILER_VERSION_C}"
    fi

before_script:
  # Move to build directory.
  - cd ${TRAVIS_BUILD_DIR}
    
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      # Use a toolchain file to force a 32 bit environment
      COMPILER_SETTINGS="${COMPILER_SETTINGS} -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/cmake/Linux_32bit_toolchain.cmake"
    fi
    
  - bash ${TRAVIS_BUILD_DIR}/travis_install_dependencies.sh ${DEPENDENCIES_DIR} "${COMPILER_SETTINGS}"
  
  - mkdir build && cd build

script:
  # Just execute the cmake and make commands
  # Use the local vgui library
  # TODO: SDL should be found by CMake at all times, this needs fixing - Solokiller
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cmake ${COMPILER_SETTINGS} -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -m32 -fno-strict-overflow -w" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -m32 -fno-strict-overflow -w" \
      -DSTEAMCOMMON=${STEAMCOMMON_DIR} ${BUILD_RULES} \
      -Dvgui_DIR="${TRAVIS_BUILD_DIR}/lib/public" \
      -DXercesC_DIR="${DEPENDENCIES_DIR}/xercesc/install/lib/cmake/XercesC" \
      ..
    else
      cmake -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -m32 -fno-strict-overflow -w" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -m32 -fno-strict-overflow -w" \
      -DSTEAMCOMMON=${STEAMCOMMON_DIR} ${BUILD_RULES} \
      -Dvgui_DIR="${TRAVIS_BUILD_DIR}/lib/public" \
      -DXercesC_DIR="${DEPENDENCIES_DIR}/xercesc/install/lib/cmake/XercesC" \
      ..
    fi
  - make

notifications:
  email: false

