#   ########   #
#   Hu3-Life   # O mod da família brasileira.
#   ########   #

#----------------#
#     Geral      #
#----------------#

# Branches que serão compiladas pelo AppVeyor.
branches:
  only:
  - master

#----------------#
#    Ambiente    #
#----------------#

# VM com VS 2017
os: Visual Studio 2017

# Configurações de build
environment:
  COMPILER_VERSION: Visual Studio 15 2017
  COMPILER_TOOLSET: v141
  matrix:
    - BUILD_RULES: -DUSE_OPFOR=1

# Se algum dos trabalhos falharem, marcar o build como ruim
matrix:
  fast_finish: true

#----------------#
#     Build      #
#----------------#

# Windows
platform: Win32

# Build em modo Release (usamos os builds do site para distruibuir os dlls)
configuration:
  - Release

# Criar pacotes de Web Deploy
build:  
  publish_wap: true

before_build:
  # Usar a última versão do CMake
  - ps: Write-Host "=== (1/5) Downloading CMake 3.11.4 ZIP for Windows 64 bits ===" -foregroundcolor green
  - ps: wget https://cmake.org/files/v3.11/cmake-3.11.4-win64-x64.zip -OutFile cmake_files.zip
  - ps: Write-Host "=== (2/5) Installing CMake ===" -foregroundcolor green
  - cmd: 7z x cmake_files.zip -o"." -y
  # Renomear o arquivo para não termo que lidar com números de versão em lugar nenhum
  - ps: Rename-Item cmake-3.11.4-win64-x64 cmake_install
  # Lidar com as dependências
  - ps: .\appveyor_install_dependencies.ps1
  # Criar o diretório de build e imitar a pasta common do Steam
  - ps: Write-Host "=== (4/5) Creating build and fake Steam common directory ===" -foregroundcolor green
  - md build_h3lenhanced
  - md fake_steamcommon

# Dar build no H3LEnhanced
build_script:
  - cd build_h3lenhanced
  - ps: Write-Host "=== (5/5) Building H3LEnhanced ===" -foregroundcolor green
  - ..\cmake_install\bin\cmake.exe -DXercesC_DIR=%APPVEYOR_BUILD_FOLDER%\dependencies\xercesc\install\cmake -DSTEAMCOMMON=..\fake_steamcommon %BUILD_RULES% -G"%COMPILER_VERSION%" -T%COMPILER_TOOLSET% ..
  - ..\cmake_install\bin\cmake.exe --build . --clean-first --config %CONFIGURATION%

# Voltar para a pasta do projeto
after_build:
  - cd ..\

#----------------#
#   Artefatos    #
#----------------#

# Pegar os arquivos de biblioteca gerados e atribuindo nomes
artifacts:
  - path: fake_steamcommon\Half-Life\Hu3-Life\cl_dlls\client.dll
    name: client.dll
  - path: fake_steamcommon\Half-Life\Hu3-Life\dlls\hl.dll
    name: hl.dll

#----------------#
#   Deployment   #
#----------------#

# Enviar artefatos direto para o Xalahost!
deploy:
 provider: Environment
 name: Xalahost
 on:
   branch: master

#----------------#
#    Testes      #
#----------------#

# Nós não temos unidades de testes
test: off
